### ISSUE TITLE
Это работает?

### ISSUE THREAD

**Issue by rasxod** [madoublet/respond6#1]
Пробовал устанавливать по инструкции, но все плохо. 
```
D:\www\respond\app>gulp
module.js:471
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\www\respond\app\gulpfile.js:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
и еще нигде ничего не сказано про composer
запустил composer 

с ним лучше

из ошибок

1 не хватает языкового файла /creat
2 /install на localhost не проходит из-за api хотя там ответ 200
3 в последующем 

> Angular is running in the development mode. Call enableProdMode() to enable the production mode.
> assets/i18n/en.json Failed to load resource: the server responded with a status of 404 (Not Found)
> main.0f89cbc80238ee5e7d6b.bundle.js:1 ERROR l
> J @ main.0f89cbc80238ee5e7d6b.bundle.js:1
> login:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
> assets/i18n/ru.json Failed to load resource: the server responded with a status of 404 (Not Found)
> main.0f89cbc80238ee5e7d6b.bundle.js:1 ERROR l
> J @ main.0f89cbc80238ee5e7d6b.bundle.js:1
> recaptcha__ru.js:493 reCAPTCHA couldn't find user-provided function: onloadCallback
> api/routes/list Failed to load resource: the server responded with a status of 500 (Internal Server Error)
> api/files/list Failed to load resource: the server responded with a status of 500 (Internal Server Error)
> api/routes/list Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by rasxod** [comment]
Вы забыли написать что нужно накатывать на depricated иначе не заработает
